# Function

### Function description

In [3]:
def student_info(name , age =22):
    print(name,age)

### Function Calling

In [4]:
student_info("Maxi")

Maxi 22


In [6]:
from math import sqrt
print(sqrt(65596))

256.117160690181


# Numpy

#### Installing numpy

In [7]:
"pip install numpy"

'pip install numpy'

#### Importing numpy

In [8]:
import numpy as np

#### Creating numpy array

In [15]:
# Creating a 1D array
x = np.array([1,2,3,4,5])
# Creating a 2D array
y = np.array([[1,2,3],[3,4,5]])
# Creating a 3D array
z = np.array([[[1,2],[2,3]],[[4,5],[5,6]],[[1,2],[2,3]],[[4,5],[5,6]]])
print(x)
print(y)
print(z)

[1 2 3 4 5]
[[1 2 3]
 [3 4 5]]
[[[1 2]
  [2 3]]

 [[4 5]
  [5 6]]

 [[1 2]
  [2 3]]

 [[4 5]
  [5 6]]]


In [19]:
import pandas as pd
s = pd.Series([10,20,30,40] , name = "MyNumbers")
print(f"Pandas Series:\n{s}")
print(f"Type of series:{type(s)}")

data = {
    'Name' : ['Alice','Bob','Charlie','David'],
    'Age': [25,30,27,29],
    'City' : ['New York','London','Paris','New York']
}
df = pd.DataFrame(data)
print(f"\nPandasDataFrame:\n{df}")

Pandas Series:
0    10
1    20
2    30
3    40
Name: MyNumbers, dtype: int64
Type of series:<class 'pandas.core.series.Series'>

PandasDataFrame:
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   27     Paris
3    David   29  New York


In [22]:
df = pd.read_csv("Hearing well-being Survey Report.csv")
df.head()

Perceived_Hearing_Meaning Hearing_FOMO  \
0  Staying independent and alert, Enjoying music,...    Sometimes   
1  Staying independent and alert, Staying connect...       Rarely   
2  Staying independent and alert, I haven’t tho...       Rarely   
3                      Staying independent and alert    Yes often   
4                      Staying independent and alert        Never   

  Hearing_Test_Barrier                            Missed_Important_Sounds  \
0                 Cost                       Yes, in family conversations   
1  Never felt the need  Yes, in public spaces (trains, shops, announce...   
2                Shame      Yes, during important work or school meetings   
3    Lack of awareness      Yes, during important work or school meetings   
4    Lack of awareness                     No, I usually hear things well   

  Left_Out_Due_To_Hearing Daily_Headphone_Use  Belief_Early_Hearing_Care  \
0              Yes, often        My parent(s)                          5   
1    Only in noisy places   My child/children                          5   
2               Sometimes        My parent(s)                          5   
3               Sometimes           1-2 hours                          4   
4    Only in noisy places    Less than 1 hour                          5   

                    Last_Hearing_Test_Method  \
0  Self - application, Loved one, AI Support   
1                         Self - application   
2                         Self - application   
3            I've never taken a hearing test   
4            I've never taken a hearing test   

            Interest_in_Hearing_App  \
0                               Yes   
1                               Yes   
2                             Maybe   
3        Yes, that would be helpful   
4  No, I don't think it's necessary   

                                Desired_App_Features  \
0  Privacy, Soft guidance, Visuals, Report sharin...   
1                                            Privacy   
2                                      Soft guidance   
3                             Game-based interaction   
4  Quick tests, Game-based interaction, Detailed ...   

  Awareness_on_hearing_and_Willingness_to_invest  \
0                                            Yes   
1                                            Yes   
2                                             No   
3                                            Yes   
4                                             No   

                      Paid_App_Test_Interest Age_group  \
0             Maybe, if it offers good value   18 - 24   
1  No, I prefer getting tested at a hospital   18 - 24   
2                            Yes, definitely   18 - 24   
3                            Yes, definitely   18 - 24   
4  No, I prefer getting tested at a hospital   25 - 34   

  Ear_Discomfort_After_Use  
0                       No  
1                      Yes  
2                    Maybe  
3             Occasionally  
4                       No

In [29]:
df = pd.read_csv("2019.csv")
df.head()

Institute  \
0  Indian Institute of Technology Bhubaneswar   
1  Indian Institute of Technology Bhubaneswar   
2  Indian Institute of Technology Bhubaneswar   
3  Indian Institute of Technology Bhubaneswar   
4  Indian Institute of Technology Bhubaneswar   

                               Academic Program Name Quota   Seat Type  \
0  Civil Engineering (4 Years, Bachelor of Techno...    AI        OPEN   
1  Civil Engineering (4 Years, Bachelor of Techno...    AI        OPEN   
2  Civil Engineering (4 Years, Bachelor of Techno...    AI  OPEN (PwD)   
3  Civil Engineering (4 Years, Bachelor of Techno...    AI         EWS   
4  Civil Engineering (4 Years, Bachelor of Techno...    AI         EWS   

                                  Gender Opening Rank Closing Rank  Year  \
0                         Gender-Neutral         6546         7720  2019   
1  Female-only (including Supernumerary)        11238        13803  2019   
2                         Gender-Neutral         119P         119P  2019   
3                         Gender-Neutral          736          770  2019   
4  Female-only (including Supernumerary)         1694         1694  2019   

   Round  
0      1  
1      1  
2      1  
3      1  
4      1